### PR TITLE
Replace the method to show SFSafariViewController

### PR DESCRIPTION
**Pull request by touyou**
## What

I replace the method to show SFSafariViewController because I found some usability problem of current methods.
This is how the interaction has changed.

Before

https://github.com/tryswift/trySwiftTokyoApp/assets/465697/8a23fdc1-2432-4d33-a809-a3b30b22a7b2

After

https://github.com/tryswift/trySwiftTokyoApp/assets/465697/99dd4aba-5f26-4806-93d2-ade608a05240

## Why

I found these problems:

- SFSafariViewController enables users to close by edge swipe, so users can close sheet of Safari by edge swipe.
- When scrolling web page, top toolbar get weird. This is because SFSafariViewController cannot recognize top toolbar height inside sheet correctly.

## How

I'm TCA beginner, so sorry for implementing it by UIApplication extension functions.
I replaced these view:

- ScheduleFeature
  - Detail
  - ~~Schedule~~ ← Revert it
- trySwiftFeature
  - Acknowledgements
  - Profile
  - trySwift

And not replace Sponsors because it already uses `fullScreenCover`.
According to this [article](https://sarunw.com/posts/sfsafariviewcontroller-in-swiftui/), `fullScreenCover` still has usability problem, but it's not critical and I decided not to replace it.

### CODE REVIEW

**Comment by d-date** [comment]
HI @touyou ,

Thank you for improving SF Safari experience.
It might be create Safari dependency value instead of using Safari module.

See how it work and cherry-pick my commit to improve your pull request.
https://github.com/tryswift/trySwiftTokyoApp/tree/safari

**Comment by d-date** [comment]
This might be help for you to check diff. I have no plan to merge my PR. Please try to complete your work!
https://github.com/tryswift/trySwiftTokyoApp/pull/48

**Comment by touyou** [comment]
@d-date Thanks for very helpful commit and advice!
I try to complete it tonight or tomorrow!

**Review by d-date — APPROVED** [review]
Thank you!

**Pull request merged**
