### PR TITLE
Add AppIconStack for visionOS.

### PR DESCRIPTION
**Pull request by noppefoxwolf**
CleanShot 2024-03-14 at 14 59 55

### CODE REVIEW

**Comment by d-date** [comment]
@noppefoxwolf Looks so cute!
How can we use this Riko?  Let me know what I need to export from ai file.
https://github.com/tryswift/riko/blob/main/vision.ai

**Comment by noppefoxwolf** [comment]
Sorry I don't have adobe illustrator. 😂
So, I exported images by Sketch.

**Comment by d-date** [comment]
Screenshot 2024-03-15 at 20 01 07

**Review by d-date — APPROVED** [review]
Thank you!

**Pull request merged**
